# -*- coding: utf-8 -*-
"""Week 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taNRp-Vas8M7xwCqNDE6zBFYe1RV-zrW
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/project/healthcare_dataset.csv")

df.columns

df.isnull()

df.isnull().sum()

df['Admission_Date']=pd.to_datetime(df['Admission_Date'], dayfirst=True)
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'], dayfirst=True)

df["No_of_days_stay"]=df["Discharge_Date"]-df["Admission_Date"]

df['No_of_days_stay'].head()

billing=df.groupby(['Medical_Condition'])['Billing_Amount'].sum()
billing

billing.plot(kind='bar',figsize=(10,6), stacked=True)

plt.figure(figsize=(10,6))
sns.violinplot(data=df,
               x='Medical_Condition',
               y='Billing_Amount')

plt.figure(figsize=(10,6))
sns.violinplot(data=df,
               x='Admission_Type',
               y='Billing_Amount')

df['Admission Month']=df['Admission_Date'].dt.month
df['Admission Month']

monthly_sub=df.groupby('Admission Month').size()
monthly_sub

monthly_sub.plot()

Corr_matrix=df[['Age','No_of_days_stay', 'Billing_Amount']].corr()
Corr_matrix

sns.heatmap(Corr_matrix, annot=True, cmap="coolwarm")